"""
Card AC.1 -- serial dependence in each design: how far can the first study be trusted?

THE PRE-REGISTRATION. Written 2026-09-25, before this was computed.

WHY. Jonas, 2026-09-25: *"We cannot trust study one. There is too much autocorrelation. I think we
have said that before, or?"* The record (`docs/czb_study1_data_plan.md` §2(b), decision 8,
2026-08-26; handbook appendix 15) excluded the first study's SEQUENCE paradigm for autocorrelation,
carried its RANDOM paradigm forward as the primary fitting source, and kept its BUTTON paradigm for
validation only (satisficing, anticipation). Cards NC.3j, NC.3m and NC.3n then used the Button
paradigm as a primary source for the hard boundary, against decision 8. Before deciding what to
keep, the serial dependence is measured, design by design, the same way.

WHAT IS COMPUTED. For each design, the binary "would intervene" response (Button: a press) in
presentation order within participant and session (`Trial_Nr` within `Rec_Session_Id`; study 2:
within `Exp_Subject_Id`). The residual r_t = y_t - mean(y | cell), with the cell the stimulus
(Sequence and Random: scenario x criticality x the clip's stop point; Button: scenario x
criticality; study 2: the video). The statistic is the lag-1 correlation of r_t with r_{t-1}
(consecutive trials of the same participant and session, any scenario), with a 95% bootstrap
interval over participants (200). A second version restricted to consecutive trials of the SAME
scenario is reported beside it.
  designs: study 1 Sequence (the positive control: excluded for this reason), study 1 Random,
  study 1 Button, study 2.

THE RULE, per design: MATERIAL if the lag-1 residual correlation exceeds 0.10 with an interval
excluding zero; PRESENT BUT SMALL if the interval excludes zero and it is at most 0.10; NOT
DETECTED otherwise. Rule 0: the Sequence design must come out MATERIAL, else the statistic does not
detect what the record says is there, and the card says so.

PREDICTIONS. Sequence 0.3 or more (MATERIAL); Random 0.05 to 0.10 (PRESENT BUT SMALL); Button about
0.10 (borderline); study 2 about 0.05 (PRESENT BUT SMALL).

Output: replication/czb/out/ac1_serial_dependence.md
Run:    python replication/czb/ac1_serial_dependence.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(REPO / "src"))
import cutin2_field_vs_gap as R  # noqa: E402
from comfortzone.czb_data import STUDY, load_joint  # noqa: E402

OUT = HERE / "out"


def lag1(df, y, cell, seq, pid):
    d = df.dropna(subset=[y]).copy()
    d["r"] = d[y] - d.groupby(cell)[y].transform("mean")
    d = d.sort_values(seq + ["Trial_Nr"])
    d["r_prev"] = d.groupby(seq).r.shift(1)
    d["scen_prev"] = d.groupby(seq)["scenario"].shift(1)
    d = d.dropna(subset=["r_prev"])
    same = d[d.scenario == d.scen_prev]

    def corr(x):
        return float(np.corrcoef(x.r, x.r_prev)[0, 1]) if len(x) > 10 else np.nan
    rng = np.random.default_rng(20260925)
    ids = d[pid].unique()
    bs, bs2 = [], []
    for _ in range(200):
        pick = rng.choice(ids, len(ids))
        bb = pd.concat([d[d[pid] == p] for p in pick])
        bs.append(corr(bb))
        bs2.append(corr(bb[bb.scenario == bb.scen_prev]))
    return (corr(d), np.nanpercentile(bs, [2.5, 97.5]), corr(same), np.nanpercentile(bs2, [2.5, 97.5]),
            len(d), d[pid].nunique())


def verdict(r, ci):
    if ci[0] > 0 or ci[1] < 0:
        return "MATERIAL" if abs(r) > 0.10 else "PRESENT BUT SMALL"
    return "NOT DETECTED"


def main() -> None:
    res = {}
    s = pd.read_csv(STUDY / "Sequence_Random_Combined_Data.csv", low_memory=False)
    seq = s[s.Study_Design.astype(str).str.contains("Seq", case=False)].copy()
    seq["y"] = pd.to_numeric(seq.CZB_1, errors="coerce")
    res["study 1, Sequence (positive control)"] = lag1(
        seq, "y", ["scenario", "crit_label", "Trial_Id"], ["Rec_Session_Id"], "Exp_Subject_Id")
    j = load_joint()
    rnd = j[j.design == "Random"].copy()
    res["study 1, Random (the primary source)"] = lag1(
        rnd, "intervene", ["scenario", "criticality_label", "timepoint"], ["Rec_Session_Id"], "Exp_Subject_Id")
    btn = j[j.design == "Button"].copy()
    res["study 1, Button (validation only)"] = lag1(
        btn, "intervene", ["scenario", "criticality_label"], ["Rec_Session_Id"], "Exp_Subject_Id")
    t2 = pd.read_csv(R.TRIALS, low_memory=False)
    t2 = t2[~t2.video.str.contains("dummy")].copy()
    t2["scenario"] = "cutin"
    res["study 2 (cut-in only)"] = lag1(t2, "CZB_1", ["video"], ["Exp_Subject_Id"], "Exp_Subject_Id")

    L = ["# Card AC.1 -- serial dependence, design by design", "",
         "Generated by `replication/czb/ac1_serial_dependence.py`; pre-stated in its docstring before"
         " the run. Do not edit by hand.", "",
         "Lag-1 correlation of consecutive residuals (response minus its stimulus cell's mean), within"
         " participant and session; 95% bootstrap over participants.", "",
         "| design | pairs | participants | lag-1, any scenario | 95% | lag-1, same scenario | 95% |"
         " verdict |", "|---|---|---|---|---|---|---|---|"]
    for k, (r, ci, r2, ci2, n, p) in res.items():
        L.append(f"| {k} | {n:,} | {p} | **{r:+.3f}** | [{ci[0]:+.3f}, {ci[1]:+.3f}] | {r2:+.3f} |"
                 f" [{ci2[0]:+.3f}, {ci2[1]:+.3f}] | {verdict(r, ci)} |")
    ctrl = res["study 1, Sequence (positive control)"]
    L += ["", f"Rule 0 (the Sequence design must be MATERIAL): **{'PASS' if verdict(ctrl[0], ctrl[1]) == 'MATERIAL' else 'FAIL'}**.", ""]
    (OUT / "ac1_serial_dependence.md").write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
