"""Collect the open queries raised by executing sessions into one register.

Executing sessions raise numbered queries in the work log rather than stopping to ask
(`~/.claude/skills/performing-research/SKILL.md` sections 1-3). Each is written inline as

    @<card>.Q<n>(<severity>): <text>

with severity one of blocker, judgment, minor. This script scans the work log and emits
`out/query_register.md`, ordered by severity so that blockers are read first -- with nine
open queries the severity mattered more than the numbering, which is why the register is
generated rather than read off the log in card order.

The register is derived, never hand-edited: the work log is the source of truth, so a
query cannot be silently dropped from the register without being dropped from the log.
Resolutions are recorded by adding a `RESOLVED <card>.Q<n>: ...` line to the log, which
moves the query into the closed section here.

    python replication/czb/collect_queries.py
"""
from __future__ import annotations

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
LOG = HERE / "out" / "worklog.md"
DEST = HERE / "out" / "query_register.md"

SEVERITY_ORDER = {"blocker": 0, "judgment": 1, "minor": 2}
QUERY = re.compile(r"@([A-Z][\w.]*?)\.Q(\d+)\((blocker|judgment|minor)\)\s*:\s*(.*)",
                   re.DOTALL)
RESOLVED = re.compile(r"^RESOLVED\s+([A-Z][\w.]*?)\.Q(\d+)\s*:\s*(.*)$", re.MULTILINE)


def parse(text: str):
    """Every query in the log, with its text running to the next query or heading."""
    out = []
    for m in re.finditer(r"@[A-Z][\w.]*?\.Q\d+\((?:blocker|judgment|minor)\)", text):
        start = m.start()
        nxt = re.search(r"\n@[A-Z][\w.]*?\.Q\d+\(|\n## ", text[m.end():])
        body = text[start:m.end() + (nxt.start() if nxt else len(text) - m.end())]
        q = QUERY.match(body)
        if q:
            card, num, sev, msg = q.groups()
            out.append({"card": card, "n": int(num), "severity": sev,
                        "text": " ".join(msg.split())})
    return out


def main() -> None:
    text = LOG.read_text(encoding="utf-8")
    queries = parse(text)
    closed = {(c, int(n)): t for c, n, t in RESOLVED.findall(text)}

    open_q = [q for q in queries if (q["card"], q["n"]) not in closed]
    open_q.sort(key=lambda q: (SEVERITY_ORDER[q["severity"]], q["card"], q["n"]))

    L = ["# Query register\n",
         "Generated by `replication/czb/collect_queries.py` from "
         "`replication/czb/out/worklog.md`, which is the source of truth. Do not edit "
         "this file by hand.\n",
         f"**{len(open_q)} open** "
         f"({sum(q['severity'] == 'blocker' for q in open_q)} blocker, "
         f"{sum(q['severity'] == 'judgment' for q in open_q)} judgment, "
         f"{sum(q['severity'] == 'minor' for q in open_q)} minor); "
         f"{len(closed)} resolved.\n"]

    current = None
    for q in open_q:
        if q["severity"] != current:
            current = q["severity"]
            L.append(f"\n## {current.capitalize()}\n")
        L.append(f"**{q['card']}.Q{q['n']}** — {q['text']}\n")

    if closed:
        L.append("\n## Resolved\n")
        for (card, n), t in sorted(closed.items()):
            L.append(f"**{card}.Q{n}** — {' '.join(t.split())}\n")

    DEST.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"{len(open_q)} open queries, {len(closed)} resolved -> {DEST}")
    for q in open_q:
        print(f"  [{q['severity']:9s}] {q['card']}.Q{q['n']}: {q['text'][:70]}...")


if __name__ == "__main__":
    main()
