"""
Card DT.1b -- how DT.1's display-dependent conclusions move with the display parameters.

THE PRE-REGISTRATION. Written 2026-09-26, after card DT.1, before this was computed.

WHY. Jonas: the parameters (60 cm, 23-inch screen, 90 degree rendering field of view) "can/will
change later". Card DT.1 found that the within-study results do not depend on them, but four
cross-domain conclusions do, all through the gain k = (image width / 2) / (d tan(HFOV / 2)). This
card shows how far those conclusions move over plausible values, so that the parameters can be
fixed knowing what rides on them.

GRID. Viewing distance 50, 60, 70 cm x image width fraction 1.0, 0.8, 0.6 (full-screen video, or a
video in a browser window), the other parameters at the spec's defaults; plus the untransformed
case (k = 1). For each: k; card JJ.10's mixture refitted on the perceived looming (level, spread;
post-onset held out); its 50% level as a multiple of Farewell's 0.02 rad/s (card PT.1); on highD's
closing cut-ins (card NC.3, detector 0.5 m/s^2 / 0.3 s) its predicted response rate against the
observed and its binned wRMSE; card NC.3h's matching deceleration (no lapse, all closing cut-ins,
no bootstrap).

EXPECTATION (stated, no rule: this is a sensitivity table). The level scales with k; the 50% level
falls below Farewell's at every k below about 0.6; the matching deceleration falls with k, between
about 0.5 and 0.8 m/s^2 over the grid; the held-out score does not move.

Output: replication/czb/out/dt1b_display_sensitivity.md
Run:    python replication/czb/dt1b_display_sensitivity.py
"""
from __future__ import annotations

import sys
import time
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.special import expit
from scipy.stats import norm

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import dt1_display_transform as DT  # noqa: E402

D, J10, J6, CL, N, H, P1 = DT.D, DT.J10, DT.J6, DT.CL, DT.N, DT.H, DT.P1
OUT = HERE / "out"


def main() -> None:
    warnings.filterwarnings("ignore")
    t0 = time.time()
    cells = pd.read_csv(OUT / "cutin2_cells.csv")
    W, _ = CL.widths_for(cells)
    gap = cells.distance.to_numpy(float)
    dv = cells.dv_kph.to_numpy(float) * DT.KPH
    lat = J6.CG.lateral_states(cells.video)
    base = cells[["video", "cp", "p", "n", "ttc_start", "ttc_true", "distance", "dv_kph"]].copy()
    base["p_lead"] = DT.p_lead(lat.l0.to_numpy(float), lat.ldot.to_numpy(float), DT.SIGMA_LAT, DT.T_ANTICIPATION)
    _, ev = pd.read_pickle(N.CACHE)
    e = ev[~ev["pre_0.5_0.3"] & ~ev.lc]
    c = e[e.dv > 0]
    yh = c["resp_0.5_0.3"].to_numpy(bool)
    xh = np.log((c.W * c.dv / (c.gap ** 2 + c.W ** 2 / 4)).to_numpy(float))
    bins = pd.qcut(xh, 10, labels=False, duplicates="drop")
    ev3, _ = pd.read_pickle(H.CACHE)
    c3 = ev3[~ev3.lc & (ev3.dv > 0)].reset_index(drop=True)
    geos = [("none (rendered world)", None)] + [
        (f"{d:g} cm, image {f:g} of the screen", D.load_geometry(viewing_distance_cm=d, image_width_fraction=f))
        for d in (50, 60, 70) for f in (1.0, 0.8, 0.6)]
    L = ["# Card DT.1b -- DT.1's display-dependent conclusions over the display parameters", "",
         "Generated by `replication/czb/dt1b_display_sensitivity.py`; pre-stated in its docstring before"
         " the run. Do not edit by hand. Screen 23-inch 16:9, rendering HFOV 90 deg throughout.", "",
         f"highD closing cut-ins: {len(yh):,}, observed response rate {yh.mean():.3f}.", "",
         "| geometry | k | video level [rad/s] | spread | held out (study 2) | 50% level / Farewell's |"
         " highD predicted rate | highD binned wRMSE | NC.3h matching decel. [m/s^2] |",
         "|---|---|---|---|---|---|---|---|---|"]
    for lab, g in geos:
        d = base.copy()
        d["theta_dot"] = D.looming(gap, dv, W, g)
        r = J10.score("mixture", d)
        lap, lv, sp = float(expit(r["theta"][0])), float(np.exp(r["theta"][1])), float(np.exp(r["theta"][2]))
        fifty = np.exp(np.log(lv) + sp * norm.ppf((0.5 - lap) / (1 - lap)))
        pr = lap + (1 - lap) * norm.cdf((xh - np.log(lv)) / sp)
        wr, _ = N.binned_wrmse(pr, yh, bins)
        H.INT_LEVEL, H.INT_SPREAD = lv, sp
        a_m, _ = H.matching(c3, "int", 0.0, {"c": 0.0, "s": 1.0})
        L.append(f"| {lab} | {D.gain(g):.3f} | {lv:.4f} | {sp:.3f} | {r['post']:.4f} |"
                 f" {fifty / P1.FAREWELL_THETA_DOT:.2f} | {pr.mean():.3f} | {wr:.4f} | {a_m:.2f} |")
        print(f"{lab} [{time.time() - t0:.0f} s]", flush=True)
    L += ["", f"Run time {time.time() - t0:.0f} s.", ""]
    (OUT / "dt1b_display_sensitivity.md").write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
