"""
Card JJ.2d -- card JJ.2 restated on the single-Gaussian fan: no intention mixture, no keeper clip.

THE PRE-REGISTRATION. Written before the run, on 2026-09-22.

WHY. Card JJ.6e showed that the gate of the measurement model is the fan's own P(in my path
within 3 s) once the fan is a single Gaussian-rate hypothesis with no lane-edge clip, and that
card JJ.1's intention mixture (changers at a fixed 1.2 m/s, keepers clipped at a lane edge) is
what stopped the belief from grading. Jonas (2026-09-22): make the single Gaussian the default,
"or at least try it". Every earlier JJ card ran on the mixture fan, so the arc's one surviving
verdict, JJ.2's DROP of Delta G, is restated here on the fan that can express the gate. Nothing
else changes: card JJ.2's cells, belief at the freeze, menu, preference stagings (the project's
and the released, as JJ.2c), folds, metric, both fit signs.

WHAT IS COMPUTED. `jj2c_released_flags.run` with the fan drawn as `sample_futures(...,
keeper_bound=False)` and `b.p_change = 0.0` (one hypothesis). Both stagings, sign +1 and -1.

THE RULES. Card JJ.2's, verbatim, on the project staging at sign +1: (a) within 0.01 of 0.1027,
(b) pre-onset below 0.05, (c) 24 of 24 rows. ADOPT / COMPARATOR / DROP.

PREDICTION. DROP again: the fan changes which futures collide, not the horizon sum that inverts
every rollout quantity (review checks section 1; JJ.5b). Post-onset 0.30 to 0.32 at +1 and 0.25
to 0.30 at -1; rho(gap) positive. Pre-onset: G(continue) is now small in the pre-onset cells
(only the Gaussian tail collides), so rule (b)'s number will look better than JJ.2's 0.5381 --
0.2 to 0.4 -- without meaning anything, because the post-onset fit is still a constant.

Output: replication/czb/out/jj2d_gaussian_fan.md, out/jj2d_gaussian_fan_cells.csv
Run:    python replication/czb/jj2d_gaussian_fan.py
"""
from __future__ import annotations

import sys
import time
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(REPO / "src"))

import hs1_situational_surprise as HS      # noqa: E402
import jj2_rollout_cutin as J2             # noqa: E402
import jj2c_released_flags as J2C          # noqa: E402
from aidriver.preferences import PreferenceParams  # noqa: E402
from rollout.belief import FLOORS_STUDY2, belief_at  # noqa: E402
from rollout.boundary import delta_g  # noqa: E402
from rollout.efe import g_by_policy  # noqa: E402
from rollout.policies import CUTIN_MENU, ego_rollout  # noqa: E402
from rollout.predictor import DT_S, HORIZON_S, N_SAMPLES, SD_A, SD_VLAT, sample_futures  # noqa: E402

OUT = HERE / "out"


def run(cells, scenes, released):
    rows = []
    for v in cells.video:
        key, e_t, cp = J2.trace_key(v)
        b = belief_at(J2.scene_of(scenes[key], key), e_t, FLOORS_STUDY2, with_intention=False)
        b.p_change = 0.0
        fut = sample_futures(b, horizon_s=HORIZON_S, dt=DT_S, n=N_SAMPLES, sd_vlat=SD_VLAT,
                             sd_a=SD_A, seed=0, keeper_bound=False)
        paths = {k: ego_rollout(b, k, HORIZON_S, DT_S) for k in CUTIN_MENU}
        p = (PreferenceParams(v_desired=b.v_ego) if released else
             PreferenceParams(v_desired=b.v_ego, lane_entry_continuous=True,
                              counterfactual_residual_severity=True,
                              lane_entry_shape_k=J2.CZB_LANE_ENTRY_SHAPE_K))
        g = g_by_policy(b, fut, paths, p)
        rows.append({"video": v, "cp": cp, "dg": delta_g(g), "G_continue": g["continue"]})
    return pd.DataFrame(rows)


def main() -> None:
    warnings.filterwarnings("ignore")
    t0 = time.time()
    cells = pd.read_csv(OUT / "cutin2_cells.csv")
    scenes = HS.study2_scenes(cells)
    proj, rel = run(cells, scenes, False), run(cells, scenes, True)
    sp, sr = J2C.score(proj, cells), J2C.score(rel, cells)
    proj.merge(rel[["video", "dg"]].rename(columns={"dg": "dg_released"}), on="video").to_csv(
        OUT / "jj2d_gaussian_fan_cells.csv", index=False)
    a, b = sp["post"] <= J2C.G1_GATED + 0.01, sp["cp1"] < 0.05
    verdict = "ADOPT" if a and b else ("COMPARATOR" if a else "DROP")
    L = ["# Card JJ.2d -- card JJ.2 on the single-Gaussian fan", "",
         "Generated by `replication/czb/jj2d_gaussian_fan.py`; pre-stated in its docstring before"
         " the run. Do not edit by hand.", "",
         "| staging | post-onset held out, sign +1 | sign -1 | pre-onset | matched-TTC rows |"
         " rho(dG, share) | rho(dG, gap) | zero cells |", "|---|---|---|---|---|---|---|---|"]
    for lab, s in (("the project's staging (JJ.2's)", sp), ("released", sr)):
        L.append(f"| {lab} | {s['post']:.4f} | {s['neg']:.4f} | {s['cp1']:.4f} | {s['rows']} of"
                 f" {s['n_rows']} | {s['rho_p']:+.3f} | {s['rho_gap']:+.3f} | {s['zeros']} |")
    L += ["", f"On the mixture fan (cards JJ.2, JJ.2c): 0.3202 / 0.2515 / 0.5381 and 0.3197 /"
          f" 0.3302 / 0.9510.", "",
          f"**{verdict}** on card JJ.2's rules (project staging, sign +1): (a) {sp['post']:.4f}"
          f" against 0.1127, (b) {sp['cp1']:.4f} against 0.05, (c) {sp['rows']} of 24.", "",
          f"Run time {time.time() - t0:.0f} s.", ""]
    (OUT / "jj2d_gaussian_fan.md").write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
