"""
Card NC.3b -- the detector sweep beside card NC.3's primary result, as the naturalistic plan
requires of every response-dependent card (`docs/naturalistic_data_plan.md` §2, NC.0b: "every
response-dependent card reports the sweep beside its primary result").

Written 2026-09-24, after card NC.3's run, because NC.3's script reported only the primary
setting (a_th 0.5 m/s^2, T_min 0.3 s). A sensitivity, not a card: no rule, nothing chosen. For
every (a_th, T_min) of NC.0b's grid it recomputes, on the same cached events and with the same
censoring, NC.3's quantities: the closing cut-ins' response rate, rule (a) (the video curve's
binned weighted RMSE against chance) and rule (b) (the AUCs of looming, gap and TTC).

Output: replication/czb/out/nc3b_detector_sweep.md
Run:    python replication/czb/nc3b_detector_sweep.py   (needs card NC.3's cache)
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import norm

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import nc3_highd_cutins as N  # noqa: E402

OUT = HERE / "out"


def main() -> None:
    fp_all, ev = pd.read_pickle(N.CACHE)
    lap, th0, s = N.VIDEO["JJ.10 mixture (study 2)"]
    L = ["# Card NC.3b -- the detector sweep beside card NC.3", "",
         "Generated by `replication/czb/nc3b_detector_sweep.py`; a sensitivity over NC.0b's grid"
         " on card NC.3's cached events; nothing is chosen here. Do not edit by hand.", "",
         "| a_th [m/s^2] | T_min [s] | false-positive rate | closing events | response rate |"
         " video curve wRMSE | chance | (a) | AUC looming / gap / TTC |",
         "|---|---|---|---|---|---|---|---|---|"]
    for a in N.A_GRID:
        for t in N.T_GRID:
            pre, resp = f"pre_{a}_{t}", f"resp_{a}_{t}"
            e = ev[~ev[pre] & ~ev.lc & (ev.dv > 0)].copy()
            y = e[resp].to_numpy(bool)
            if y.sum() < 10:
                L.append(f"| {a:g} | {t:g} | {fp_all[(a, t)][0] / fp_all[(a, t)][1]:.3f} | {len(e)} |"
                         f" {y.mean():.3f} | - | - | too few responses | - |")
                continue
            td = e.W * e.dv / (e.gap ** 2 + e.W ** 2 / 4)
            x = np.log(td.to_numpy(float))
            bins = pd.qcut(x, 10, labels=False, duplicates="drop")
            pv = lap + (1 - lap) * norm.cdf((x - np.log(th0)) / s)
            r_v, _ = N.binned_wrmse(pv, y, bins)
            r_c, _ = N.binned_wrmse(np.full(len(y), y.mean()), y, bins)
            aucs = (N.auc(x, y), N.auc(-np.log(e.gap.to_numpy(float)), y),
                    N.auc(-np.log((e.gap / e.dv).to_numpy(float)), y))
            L.append(f"| {a:g} | {t:g} | {fp_all[(a, t)][0] / fp_all[(a, t)][1]:.3f} | {len(e):,} |"
                     f" {y.mean():.3f} | {r_v:.4f} | {r_c:.4f} | {'yes' if r_v < r_c else 'no'} |"
                     f" {aucs[0]:.3f} / {aucs[1]:.3f} / {aucs[2]:.3f} |")
    L.append("")
    (OUT / "nc3b_detector_sweep.md").write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
