"""
Card NC.3c -- is the axis range-dependent? Card NC.3's rule (b) inside and outside the video
study's range.

THE PRE-REGISTRATION. Written 2026-09-24, after card NC.3 (query NC3.Q1), before this split was
computed.

WHY. Card NC.3 found that on real highD cut-ins inverse TTC orders the followers' responses better
than looming (AUC 0.739 against 0.713, difference -0.026 [-0.047, -0.005]), the reverse of the
video study (looming 0.1130 against TTC 0.1679 held out). highD's cut-ins are gentle: median gap
68 m and looming 0.0011 rad/s, below the video's smallest cell (0.0036 rad/s). If looming wins
inside the video's range and TTC outside it, the axis is range-dependent (a finding); if TTC wins
inside too, the video's looming result is a property of its design.

WHAT IS COMPUTED. Card NC.3's cached events and primary detector (a_th 0.5, T_min 0.3), closing
cut-ins, split two ways, each pre-stated:
  S1  looming at the event >= 0.0036 rad/s (the video's smallest cell) against below it;
  S2  bumper gap <= 40 m (inside the video's 1.6 to 82 m, where most of its cells sit) against > 40 m.
In each subset: the AUCs of log looming, -log gap and -log TTC for the response, and looming minus
TTC with a 95% bootstrap interval over recordings (200 resamples, seed 20260924).

THE RULE. RANGE-DEPENDENT if, in S1's in-range subset, looming minus TTC has an interval excluding
zero on the POSITIVE side while the out-of-range subset's is negative or includes zero. TTC
THROUGHOUT if the in-range difference is negative with an interval excluding zero. UNDECIDED
otherwise (the in-range interval includes zero). S2 is reported beside it and decides nothing.
Rule 0: at least 30 responses in the in-range subset, else UNDECIDED by count.

PREDICTION. UNDECIDED: the in-range subset is small (perhaps 300 to 500 events) and within it
looming and TTC are closer; I expect the difference to move toward zero or positive and the
interval to include zero.

Output: replication/czb/out/nc3c_axis_by_range.md
Run:    python replication/czb/nc3c_axis_by_range.py   (needs card NC.3's cache)
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import nc3_highd_cutins as N  # noqa: E402

OUT = HERE / "out"
LOOM_MIN, GAP_MAX = 0.0036, 40.0


def block(e: pd.DataFrame, resp: str, rng) -> dict:
    y = e[resp].to_numpy(bool)
    x = np.log((e.W * e.dv / (e.gap ** 2 + e.W ** 2 / 4)).to_numpy(float))
    g = -np.log(e.gap.to_numpy(float))
    t = -np.log((e.gap / e.dv).to_numpy(float))
    out = {"n": len(y), "resp": int(y.sum()), "rate": float(y.mean())}
    if y.sum() < 5 or y.sum() == len(y):
        return out
    out.update({"loom": N.auc(x, y), "gap": N.auc(g, y), "ttc": N.auc(t, y)})
    recs = e.rec.to_numpy()
    ur = np.unique(recs)
    diffs = []
    for _ in range(200):
        idx = np.concatenate([np.flatnonzero(recs == r) for r in rng.choice(ur, len(ur))])
        yy = y[idx]
        if yy.sum() in (0, len(yy)):
            continue
        diffs.append(N.auc(x[idx], yy) - N.auc(t[idx], yy))
    out["d"] = out["loom"] - out["ttc"]
    out["ci"] = tuple(np.percentile(diffs, [2.5, 97.5]))
    return out


def main() -> None:
    _, ev = pd.read_pickle(N.CACHE)
    pre, resp = "pre_0.5_0.3", "resp_0.5_0.3"
    c = ev[~ev[pre] & ~ev.lc & (ev.dv > 0)].copy()
    loom = c.W * c.dv / (c.gap ** 2 + c.W ** 2 / 4)
    rng = np.random.default_rng(20260924)
    parts = {"S1 in range: looming >= 0.0036 rad/s": c[loom >= LOOM_MIN],
             "S1 out of range: looming < 0.0036 rad/s": c[loom < LOOM_MIN],
             "S2 gap <= 40 m": c[c.gap <= GAP_MAX], "S2 gap > 40 m": c[c.gap > GAP_MAX],
             "all closing cut-ins (card NC.3)": c}
    res = {k: block(v, resp, rng) for k, v in parts.items()}
    L = ["# Card NC.3c -- the axis inside and outside the video study's range", "",
         "Generated by `replication/czb/nc3c_axis_by_range.py`; the splits and the rule were"
         " pre-stated in its docstring before the run. Aggregates only. Do not edit by hand.", "",
         "| subset | events | responses | rate | AUC looming | AUC gap | AUC TTC | looming - TTC"
         " [95% over recordings] |", "|---|---|---|---|---|---|---|---|"]
    for k, r in res.items():
        if "loom" not in r:
            L.append(f"| {k} | {r['n']} | {r['resp']} | {r['rate']:.3f} | - | - | - | too few |")
            continue
        L.append(f"| {k} | {r['n']:,} | {r['resp']} | {r['rate']:.3f} | {r['loom']:.3f} |"
                 f" {r['gap']:.3f} | {r['ttc']:.3f} | {r['d']:+.3f} [{r['ci'][0]:+.3f},"
                 f" {r['ci'][1]:+.3f}] |")
    inr = res["S1 in range: looming >= 0.0036 rad/s"]
    outr = res["S1 out of range: looming < 0.0036 rad/s"]
    if inr["resp"] < 30 or "ci" not in inr:
        verdict = "UNDECIDED (count)"
    elif inr["ci"][0] > 0 and ("ci" not in outr or outr["ci"][0] <= 0):
        verdict = "RANGE-DEPENDENT"
    elif inr["ci"][1] < 0:
        verdict = "TTC THROUGHOUT"
    else:
        verdict = "UNDECIDED"
    L += ["", f"**{verdict}** on the pre-stated rule (S1).", ""]
    (OUT / "nc3c_axis_by_range.md").write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
