"""
Card NC.3d -- hard braking only: where do real followers' HARD responses to cut-ins sit on the TTC
axis, and does "the comfort zone reaches TTC 20 s" survive once mild braking is ignored?

Written 2026-09-24, after card NC.5-tau, on Jonas's objection: *"the video braking is hard
braking, not only braking, so we should still define what is hard braking in the braking parts,
and ignore all low braking, as that may be just satisficing."* The video's response is a decision
to take over from an automated vehicle ("Would you intervene in this situation?"; in the button
study, a follow-up asked whether the participant would brake gently or hard). A highD follower
easing off at 0.5 m/s^2 to settle behind a new lead is ordinary speed regulation, not that event.
NC.5-tau's statement that real followers respond out to TTC 20 s and beyond counted such
decelerations, and is suspended until this card is read.

A DESCRIPTIVE card, not a verdict: the definition of "hard" needs a motivated threshold, which is
query NC3D.Q1 for Jonas. It reports, on card NC.3's cached events and censoring (censoring
recomputed at each threshold), for a_th in {0.5, 1.0, 1.5, 2.0} m/s^2 at T_min 0.3 s: the
response rate by TTC band, the share of responses at TTC >= 5 s (the released tau^-1 floor),
and the AUCs of looming, gap and TTC. Nothing is chosen by its score.

Output: replication/czb/out/nc3d_hard_braking.md
Run:    python replication/czb/nc3d_hard_braking.py   (needs card NC.3's cache)
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import nc3_highd_cutins as N  # noqa: E402

OUT = HERE / "out"
BANDS = [0, 5, 10, 20, 40, np.inf]


def main() -> None:
    _, ev = pd.read_pickle(N.CACHE)
    L = ["# Card NC.3d -- hard braking only", "",
         "Generated by `replication/czb/nc3d_hard_braking.py`; descriptive, on card NC.3's cached"
         " events. The threshold for \"hard\" is query NC3D.Q1; nothing is chosen here. Do not edit"
         " by hand.", "",
         "| a_th [m/s^2] | closing events | responses | " + " | ".join(
             f"rate at TTC {BANDS[i]:g}-{BANDS[i + 1]:g} s" for i in range(len(BANDS) - 1))
         + " | responses at TTC >= 5 s | AUC looming / gap / TTC |",
         "|---|---|---|" + "---|" * (len(BANDS) - 1) + "---|---|"]
    for a in N.A_GRID:
        pre, resp = f"pre_{a}_0.3", f"resp_{a}_0.3"
        c = ev[~ev[pre] & ~ev.lc & (ev.dv > 0)].copy()
        y = c[resp].to_numpy(bool)
        ttc = (c.gap / c.dv).to_numpy(float)
        band = pd.cut(ttc, BANDS)
        rates = pd.DataFrame({"b": band, "y": y}).groupby("b", observed=False).y.agg(["mean", "size"])
        cells = [f"{r['mean']:.3f} (n {int(r['size'])})" if r["size"] >= 5 else "-" for _, r in rates.iterrows()]
        far = y[ttc >= 5].sum()
        if y.sum() >= 5:
            x = np.log((c.W * c.dv / (c.gap ** 2 + c.W ** 2 / 4)).to_numpy(float))
            aucs = (f"{N.auc(x, y):.3f} / {N.auc(-np.log(c.gap.to_numpy(float)), y):.3f} /"
                    f" {N.auc(-np.log(ttc), y):.3f}")
        else:
            aucs = "too few"
        L.append(f"| {a:g} | {len(c):,} | {int(y.sum())} | " + " | ".join(cells)
                 + f" | {far} of {int(y.sum())} | {aucs} |")
    L += ["", "Reading guide: if the share of responses at TTC >= 5 s falls steeply as the threshold"
          " rises, the long reach of NC.5-tau was mild braking (satisficing), and the hard-braking"
          " boundary sits near the released floor; if it stays high, real drivers brake hard at long"
          " TTC too.", ""]
    (OUT / "nc3d_hard_braking.md").write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
