"""
Card NC.3e -- real followers' HARD braking to cut-ins, with "hard" at 2.5 m/s^2.

THE PRE-REGISTRATION. Written 2026-09-24, before any event was scored at these thresholds.

WHY. Jonas, 2026-09-24: the video's response is a take-over decision, not ordinary speed
regulation, so mild braking must be ignored as satisficing; and *"I think you should use an even
harder braking. A colleague just reported that the 99th percentile of braking (instances; which
means 1 hour per hundred hours, which still is a lot and not necessarily emergency) is 2.5 m/s^2.
I think we at least should use that."* The threshold 2.5 m/s^2 is therefore motivated from
outside this card: a colleague's naturalistic 99th percentile of braking instances (personal
communication, 2026-09-24; not verified here; the colleague is not named). NC.0b's grid stopped
at 2.0, so card NC.3's cache has no 2.5 threshold, and the events are re-extracted with the grid
a_th {2.5, 3.0} x T_min {0.3, 0.5, 1.0}; primary 2.5 m/s^2 at 0.3 s (NC.0b's shortest duration),
3.0 as a sensitivity. Everything else is card NC.3's `process`, unchanged: the events, the
censoring, the steady-following false-positive windows.

A CHECK ON THE MOTIVATION, from the data: the 99th percentile of longitudinal deceleration over
all highD car frames moving faster than 5 m/s (aggregated per recording as a histogram in
0.05 m/s^2 bins). highD is a motorway sample, so it is expected to be LOWER than a naturalistic
percentile over all driving.

WHAT IS REPORTED on closing cut-ins: responses (a qualifying episode starting within 3 s), the
response rate by TTC band, the share of responses at TTC >= 5 s, and, if there are at least 30
responses, card NC.3's rules (a) (the video curve against chance, binned) and (b) (AUCs of
looming, gap and TTC).

RULE 0: fewer than 30 hard responses -> the card is DESCRIPTIVE ONLY and says so; no transfer or
axis verdict is drawn from fewer.

PREDICTIONS. highD's 99th percentile 1.0 to 2.0 m/s^2 (motorway, below the colleague's figure).
Hard responses at 2.5 m/s^2: fewer than 30 (card NC.3d had 15 at 2.0), so DESCRIPTIVE ONLY; the
few there are sit mostly at TTC below 10 s. The finding would then be that real motorway cut-ins
almost never elicit the response the video measured, and that the video boundary's real-traffic
test needs events that are closer calls than highD's typical cut-in (median gap 68 m): the
tail of highD, or other data.

Output: replication/czb/out/nc3e_hard_2p5.md (aggregates only)
Run:    python replication/czb/nc3e_hard_2p5.py
"""
from __future__ import annotations

import sys
import time
import warnings
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import nc3_highd_cutins as N  # noqa: E402

OUT = HERE / "out"
CACHE = Path(r"C:\JonasLocal\D_Data_derived\nc3e_events.pkl")
A_HARD = (2.5, 3.0)
T_HARD = (0.3, 0.5, 1.0)
PRIMARY = (2.5, 0.3)
HIST_EDGES = np.arange(-15.0, 15.0001, 0.05)
BANDS = [0, 5, 10, 20, 40, np.inf]


def work(rec: int):
    N.A_GRID, N.T_GRID = A_HARD, T_HARD
    _, fp, events = N.process(rec)
    tr = pd.read_csv(N.HIGHD / f"{rec:02d}_tracks.csv", usecols=["id", "xVelocity", "xAcceleration"])
    meta = pd.read_csv(N.HIGHD / f"{rec:02d}_tracksMeta.csv", usecols=["id", "drivingDirection", "class"])
    tr = tr.merge(meta, on="id")
    tr = tr[(tr["class"] == "Car") & (tr.xVelocity.abs() > 5.0)]
    a = tr.xAcceleration * np.where(tr.drivingDirection == 1, -1.0, 1.0)
    hist, _ = np.histogram(a, HIST_EDGES)
    return rec, fp, events, hist


def main() -> None:
    warnings.filterwarnings("ignore")
    t0 = time.time()
    if CACHE.exists():
        fp_all, ev, hist = pd.read_pickle(CACHE)
    else:
        recs = sorted(int(p.name[:2]) for p in N.HIGHD.glob("*_tracks.csv"))
        with ProcessPoolExecutor(max_workers=12) as ex:
            res = list(ex.map(work, recs))
        fp_all = {k: [sum(r[1][k][0] for r in res), sum(r[1][k][1] for r in res)] for k in res[0][1]}
        ev = pd.DataFrame([e for r in res for e in r[2]])
        hist = np.sum([r[3] for r in res], axis=0)
        pd.to_pickle((fp_all, ev, hist), CACHE)
    centres = 0.5 * (HIST_EDGES[:-1] + HIST_EDGES[1:])
    cdf = np.cumsum(hist) / hist.sum()
    decel_p99 = float(-centres[np.searchsorted(cdf, 0.01)])
    decel_p999 = float(-centres[np.searchsorted(cdf, 0.001)])

    L = ["# Card NC.3e -- hard braking at 2.5 m/s^2", "",
         "Generated by `replication/czb/nc3e_hard_2p5.py`; the threshold's motivation, the rule and"
         " the predictions were pre-stated in its docstring before the run. Aggregates only. Do not"
         " edit by hand.", "",
         "## 0 The threshold, and a check on it", "",
         "2.5 m/s^2: a colleague's naturalistic 99th percentile of braking instances (Jonas,"
         " 2026-09-24; personal communication, not verified here). highD's own figure, over all car"
         " frames above 5 m/s: 99th percentile of deceleration"
         f" **{decel_p99:.2f} m/s^2**, 99.9th {decel_p999:.2f} m/s^2 (motorway driving).", "",
         "False-positive rate on steady following (NC.0b's windows):", "",
         "| a_th | " + " | ".join(f"T_min {t:g} s" for t in T_HARD) + " |", "|---|" + "---|" * len(T_HARD)]
    for a in A_HARD:
        L.append(f"| {a:g} | " + " | ".join(f"{fp_all[(a, t)][0] / max(fp_all[(a, t)][1], 1):.4f}"
                                          for t in T_HARD) + " |")
    L += ["", "## 1 Hard responses to closing cut-ins", "",
          "| a_th [m/s^2] | T_min [s] | closing events | hard responses | " + " | ".join(
              f"rate at TTC {BANDS[i]:g}-{BANDS[i + 1]:g} s" for i in range(len(BANDS) - 1))
          + " | at TTC >= 5 s |", "|---|---|---|---|" + "---|" * (len(BANDS) - 1) + "---|"]
    prim = None
    for a in A_HARD:
        for t in T_HARD:
            pre, resp = f"pre_{a}_{t}", f"resp_{a}_{t}"
            c = ev[~ev[pre] & ~ev.lc & (ev.dv > 0)].copy()
            y = c[resp].to_numpy(bool)
            ttc = (c.gap / c.dv).to_numpy(float)
            rates = pd.DataFrame({"b": pd.cut(ttc, BANDS), "y": y}).groupby(
                "b", observed=False).y.agg(["sum", "size"])
            cells = [f"{int(r['sum'])} of {int(r['size'])}" for _, r in rates.iterrows()]
            L.append(f"| {a:g} | {t:g} | {len(c):,} | {int(y.sum())} | " + " | ".join(cells)
                     + f" | {int(y[ttc >= 5].sum())} |")
            if (a, t) == PRIMARY:
                prim = (c, y, ttc)
    c, y, ttc = prim
    L += ["", "## 2 The verdict", ""]
    if y.sum() < 30:
        L += [f"**DESCRIPTIVE ONLY (rule 0): {int(y.sum())} hard responses at the primary setting,"
              " fewer than 30.** No transfer or axis verdict is drawn. Real motorway cut-ins almost"
              f" never elicit braking of 2.5 m/s^2: {int(y.sum())} of {len(c):,} closing cut-ins"
              f" ({y.mean():.2%}).", ""]
    else:
        x = np.log((c.W * c.dv / (c.gap ** 2 + c.W ** 2 / 4)).to_numpy(float))
        L += [f"{int(y.sum())} hard responses. AUC looming {N.auc(x, y):.3f}, gap"
              f" {N.auc(-np.log(c.gap.to_numpy(float)), y):.3f}, TTC {N.auc(-np.log(ttc), y):.3f}.", ""]
    L += [f"Run time {time.time() - t0:.0f} s.", ""]
    (OUT / "nc3e_hard_2p5.md").write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
