"""
Card NC.3f -- how many hard interventions does the video curve expect among highD's cut-ins,
against the 4 observed at 2.5 m/s^2?

Written 2026-09-24, after card NC.3e (4 hard responses in 2,771 closing cut-ins, DESCRIPTIVE ONLY
by its rule 0). This card draws no transfer verdict either; it asks the one question 4 events can
answer. Under the video population curve (card JJ.10's mixture: lapse 0.037, level 0.0320 rad/s,
spread 1.293; nothing refitted), each cut-in has a predicted probability of intervention; their
sum is the expected count. If the video's "would intervene" were real hard braking, the observed
count should be near the expected one. Reported for all closing cut-ins and for those inside the
video's looming range (>= 0.0036 rad/s), with the lapse included and removed (the lapse alone
predicts 3.7% of events), and the Poisson-binomial probability of observing at most 4 (normal
approximation to the tail is avoided: the exact distribution by convolution).

Output: replication/czb/out/nc3f_expected_hard.md
Run:    python replication/czb/nc3f_expected_hard.py   (needs card NC.3e's cache)
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import norm

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import nc3e_hard_2p5 as E  # noqa: E402

OUT = HERE / "out"
LAPSE, LEVEL, SPREAD = 0.037, 0.0320, 1.293


def p_at_most(p: np.ndarray, k: int) -> float:
    dist = np.zeros(k + 2)
    dist[0] = 1.0
    for pi in p:
        dist[1:] = dist[1:] * (1 - pi) + dist[:-1] * pi
        dist[0] *= (1 - pi)
    return float(dist[: k + 1].sum())


def main() -> None:
    _, ev, _ = pd.read_pickle(E.CACHE)
    pre, resp = "pre_2.5_0.3", "resp_2.5_0.3"
    c = ev[~ev[pre] & ~ev.lc & (ev.dv > 0)].copy()
    y = c[resp].to_numpy(bool)
    loom = (c.W * c.dv / (c.gap ** 2 + c.W ** 2 / 4)).to_numpy(float)
    core = norm.cdf((np.log(loom) - np.log(LEVEL)) / SPREAD)
    L = ["# Card NC.3f -- hard interventions expected by the video curve, against observed", "",
         "Generated by `replication/czb/nc3f_expected_hard.py`; descriptive, no verdict. Do not edit"
         " by hand.", "",
         "| subset | closing cut-ins | observed hard (2.5 m/s^2, 0.3 s) | expected, video curve with"
         " lapse | expected, without lapse | P(observed <= this), without lapse |",
         "|---|---|---|---|---|---|"]
    for lab, m in (("all", np.ones(len(c), bool)),
                   ("inside the video's looming range (>= 0.0036 rad/s)", loom >= 0.0036),
                   ("TTC below 5 s", (c.gap / c.dv).to_numpy(float) < 5)):
        pw = LAPSE + (1 - LAPSE) * core[m]
        pn = core[m]
        k = int(y[m].sum())
        L.append(f"| {lab} | {int(m.sum()):,} | {k} | {pw.sum():.1f} | {pn.sum():.1f} |"
                 f" {p_at_most(pn, k):.2e} |")
    L += ["", "Reading guide: if the observed count is far below the expected one even without the"
          " lapse, the video's \"would intervene\" is not real hard braking on the motorway: either"
          " the button press marks a lower boundary than hard braking, or real drivers tolerate more"
          " than viewers of a clip say they would.", ""]
    (OUT / "nc3f_expected_hard.md").write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
