"""
Card NC.3g -- when participants said they would intervene in a cut-in, did they mean braking
gently or hard?

Written 2026-09-24, after cards NC.3e and NC.3f (the video curve expects about 112 hard
interventions among highD's in-range cut-ins; 3 occurred). The button-press design of the first
study asked every participant who pressed during a cut-in whether they would brake GENTLY or HARD
(`button_cutin_trials().own_braking`, the study's `followup_code`; DATA_DICTIONARY gotcha 4: in the
Button design this is the participant's own action, two options). The coding is 1 or 2; that 2 is
"hard" is ASSUMED from the Random design's ordering (0 nothing, 1 gently, 2 hard) and CHECKED here
from the data: if 2 means hard, its share must rise with the clip's criticality.

Descriptive; no verdict. Output: replication/czb/out/nc3g_gentle_or_hard.md
Run:    python replication/czb/nc3g_gentle_or_hard.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
from scipy.stats import spearmanr

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO / "src"))
from comfortzone.czb_data import button_cutin_trials  # noqa: E402

OUT = HERE / "out"


def main() -> None:
    b = button_cutin_trials()
    pressed = b[(b.censored == 0) & b.own_braking.notna()].copy()
    pressed["hard"] = pressed.own_braking == 2
    by = pressed.groupby("criticality").agg(n=("hard", "size"), share_code2=("hard", "mean"),
                                             press_s=("press_since_onset", "median")).reset_index()
    by["crit_num"] = by.criticality.str.extract(r"(\d+)").astype(float)
    by = by.sort_values("crit_num")
    rho = float(spearmanr(by.crit_num, by.share_code2).statistic)
    rho_t = float(spearmanr(pressed.press_since_onset, pressed.hard, nan_policy="omit").statistic)
    L = ["# Card NC.3g -- gentle or hard? The participants' own answer", "",
         "Generated by `replication/czb/nc3g_gentle_or_hard.py`; descriptive. Do not edit by hand.", "",
         f"{len(pressed):,} button presses during cut-ins, each followed by \"would you brake gently"
         f" or hard?\". Share answering code 2: **{pressed.hard.mean():.3f}** (code 1:"
         f" {1 - pressed.hard.mean():.3f}), {pressed.participant.nunique()} participants.", "",
         "| clip label | presses | share code 2 | median press since onset [s] |", "|---|---|---|---|"]
    for _, r in by.iterrows():
        L.append(f"| {r.criticality} | {int(r.n)} | {r.share_code2:.3f} | {r.press_s:.2f} |")
    L += ["", f"Check on the coding: Spearman of the share of code 2 with the label's number"
          f" {rho:+.3f} across labels; with the press time since onset {rho_t:+.3f} across presses"
          " (a later press is a more critical moment). The label's number is a TTC in these clips, so"
          " \"2 = hard\" predicts a NEGATIVE rho with the label and a POSITIVE one with press time.",
          ""]
    (OUT / "nc3g_gentle_or_hard.md").write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
