"""
Card NC.3k -- sensitivity of the matching decelerations to exposure and to where the hard boundary
sits.

Written 2026-09-24 after cards NC.3h and NC.3j, on Jonas's two questions: *"did you control for
the different exposure?"* and *"the boundary sits at TTC 3.3 s ... seems way too high? In another
analysis, we got the 80th percentile of hard braking to be around 1 s TTC in the button data."*
A sensitivity, no rule, nothing chosen.

  EXPOSURE. The intervention curve (card JJ.10, level 0.0320 rad/s) pools both showings of every
  clip in the second study (each clip was shown twice). Card EX.2 found, on the first study, the
  first-exposure level 7.6% above the pooled one (0.0341 against 0.0317 rad/s); applied here as a
  ratio: level 0.0344. (The per-event matching already evaluates the curve at each real event's own
  looming, so the different distribution of situations in highD is accounted for; this row is
  about the participants' repeated exposure only.)
  THE HARD BOUNDARY. Card NC.3j's clip-level fit (median TTC 3.29 s, spread 0.48 log units) and
  alternatives with the median at 1.0, 1.5, 2.0 and 2.5 s, same spread. "An 80th percentile of
  hard braking at 1 s TTC" corresponds, with this spread, to a median of 1.0 x exp(0.8416 x 0.48)
  = 1.50 s if read as P(hard) = 0.8 at 1 s.

Output: replication/czb/out/nc3k_matching_sensitivity.md
Run:    python replication/czb/nc3k_matching_sensitivity.py   (needs card NC.3h's cache)
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import norm

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import nc3h_two_boundaries as H  # noqa: E402

OUT = HERE / "out"
S_T = 0.48


def match(s, level, t_med):
    x = np.log((s.W * s.dv / (s.gap ** 2 + s.W ** 2 / 4)).to_numpy(float))
    ltt = np.log((s.gap / s.dv).to_numpy(float))
    p_int = norm.cdf((x - np.log(level)) / H.INT_SPREAD)
    pred = p_int if t_med is None else p_int * norm.cdf((np.log(t_med) - ltt) / S_T)
    diff = []
    for a in H.GRID:
        keep = s.a_now.to_numpy() <= a
        diff.append((s.a_resp.to_numpy()[keep] >= a).sum() - pred[keep].sum())
    diff = np.array(diff)
    k = np.flatnonzero(np.diff(np.sign(diff)) != 0)
    if len(k) == 0:
        return np.nan, pred.sum()
    k = k[0]
    return float(H.GRID[k] + (H.GRID[k + 1] - H.GRID[k]) * diff[k] / (diff[k] - diff[k + 1])), pred.sum()


def main() -> None:
    ev, _ = pd.read_pickle(H.CACHE)
    c = ev[~ev.lc & (ev.dv > 0)].reset_index(drop=True)
    L = ["# Card NC.3k -- the matching decelerations under exposure and hard-boundary alternatives", "",
         "Generated by `replication/czb/nc3k_matching_sensitivity.py`; a sensitivity. Do not edit by"
         " hand.", "",
         "| boundary | intervention level [rad/s] | hard boundary median TTC [s] | expected responses on"
         " highD | matching deceleration [m/s^2] |", "|---|---|---|---|---|"]
    for lev, ltag in ((0.0320, "0.0320 (pooled, JJ.10)"), (0.0344, "0.0344 (first exposure, EX.2 ratio)")):
        a, e = match(c, lev, None)
        L.append(f"| intervention (gentle) | {ltag} | - | {e:.1f} | **{a:.2f}** |")
    for lev in (0.0320, 0.0344):
        for t in (3.29, 2.5, 2.0, 1.5, 1.0):
            a, e = match(c, lev, t)
            L.append(f"| hard | {lev:.4f} | {t:g}{' (NC.3j)' if t == 3.29 else ''}"
                     f"{' (80th pct at 1 s)' if t == 1.5 else ''} | {e:.1f} | **{a:.2f}** |")
    counts = [(a, int(((c.a_now <= a) & (c.a_resp >= a)).sum())) for a in (2.0, 2.5, 3.0, 3.5)]
    L += ["", "Observed responses at the upper end, for reading the hard rows: "
          + ", ".join(f"{n} at {a:g} m/s^2" for a, n in counts) + ".", ""]
    (OUT / "nc3k_matching_sensitivity.md").write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
