"""
Card NC.3l -- the hard boundary in the second cut-in study: when do participants expect the
automated vehicle to brake HARD, and does that judgment follow TTC or looming?

THE PRE-REGISTRATION. Written 2026-09-24, before this was computed. Jonas: *"what would happen if
you use study 2 for the 'hard boundary at TTC 3.3 s' analysis?"*

WHAT STUDY 2 ASKED. Not the participant's own action (the first study's button design asked that,
card NC.3j), but CZB_2: *"What would you expect your vehicle to do, assuming you do not
intervene?"* 0 nothing, 1 brake gently, 2 brake hard. So this is the TTC at which participants
judge that the situation DEMANDS hard braking of the automation -- a related construct, stated as
different in every line of the report.

WHAT IS COMPUTED. Trials of `cut-in_study_aggregate_trials_annotated.csv` (fillers dropped), the
288 post-onset cells (CP2 to CP5) and the 90 pre-onset ones. Per cell: share expecting hard (CZB_2
== 2), and the same among those who said they would intervene (CZB_1 == 1). Three axes per cell,
on the registered cells, folds (leave-one-starting-TTC-out) and metric (weighted RMSE on cell
shares) with the registered three-parameter threshold model: -log TTC_true, log looming (card
EL.1b's `looming_axis`), -log gap. The full-sample fit on -log TTC gives the hard boundary's median
TTC (the TTC at which half the cell's participants expect hard braking; lapse included).

THE RULE. Descriptive for the boundary; for the axis, the best held-out axis is named, and TTC or
looming is PREFERRED only if it beats the other by 0.01 (the project's margin), else
INDISTINGUISHABLE.

PREDICTIONS. The boundary is at a SHORTER TTC than the button study's 3.3 s for own hard braking --
about 2 to 2.5 s -- because "expect the car to brake hard" is a judgment of necessity, stricter
than one's own inclination. On the axis: TTC and looming within 0.01 of each other
(INDISTINGUISHABLE), since the intervention itself preferred looming by 0.055 on this design and
"hard" is a more urgent judgment for which a tau-like quantity is the classic cue.

Output: replication/czb/out/nc3l_expected_hard_study2.md
Run:    python replication/czb/nc3l_expected_hard_study2.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import cutin2_field_vs_gap as R   # noqa: E402
import jj6_belief_gate as J6      # noqa: E402

OUT = HERE / "out"


def held_out(x, y, w, folds, sign=+1.0):
    pred = np.full_like(y, np.nan)
    for f in np.unique(folds):
        th = R.fit(x[folds != f], y[folds != f], w[folds != f], sign)
        pred[folds == f] = R.predict(th, x[folds == f], sign)
    return R.wrmse(y, pred, w)


def main() -> None:
    tr = pd.read_csv(R.TRIALS, low_memory=False)
    tr = tr[~tr.video.str.contains("dummy") & tr.TTC_true.notna()]
    g = tr.groupby("video").agg(n=("CZB_2", "size"), hard=("CZB_2", lambda v: float(np.mean(v == 2))),
                                gentle=("CZB_2", lambda v: float(np.mean(v == 1))),
                                n_int=("CZB_1", "sum")).reset_index()
    hint = tr[tr.CZB_1 == 1].groupby("video").CZB_2.apply(lambda v: float(np.mean(v == 2))).rename("hard_given_int")
    cells = pd.read_csv(OUT / "cutin2_cells.csv")
    d = cells.merge(g, on="video").merge(hint, on="video", how="left")
    d["x_loom"] = J6.looming_axis(d)
    post = d[d.cp != "CP1"].reset_index(drop=True)
    y, w, f = post.hard.to_numpy(float), post.n.to_numpy(float), post.ttc_start.to_numpy(float)
    axes = {"-log TTC": -np.log(post.ttc_true.to_numpy(float)), "log looming": post.x_loom.to_numpy(float),
            "-log gap": -np.log(post.distance.to_numpy(float))}
    res = {k: held_out(x, y, w, f) for k, x in axes.items()}
    chance = R.wrmse(y, np.full(len(y), np.average(y, weights=w)), w)
    th = R.fit(axes["-log TTC"], y, w, +1.0)
    t50 = float(np.exp(-th[1]))
    by_ttc = post.groupby("ttc_true").apply(lambda s: pd.Series({
        "n": s.n.sum(), "hard": np.average(s.hard, weights=s.n),
        "hard_given_int": np.nanmean(s.hard_given_int)})).reset_index()
    best = min(res, key=res.get)
    diff = res["-log TTC"] - res["log looming"]
    ax_verdict = ("INDISTINGUISHABLE" if abs(diff) < 0.01 else
                  ("TTC PREFERRED" if diff < 0 else "LOOMING PREFERRED"))
    L = ["# Card NC.3l -- the hard boundary in the second cut-in study (expected vehicle action)", "",
         "Generated by `replication/czb/nc3l_expected_hard_study2.py`; pre-stated in its docstring"
         " before the run. Do not edit by hand.", "",
         "**Construct:** \"What would you expect your vehicle to do, assuming you do not intervene?\""
         " -- a judgment of what the situation demands of the automation, NOT the participant's own"
         " action (the first study's button design, card NC.3j, asked that).", "",
         f"Post-onset cells: {len(post)}; share expecting hard braking, weighted mean"
         f" {np.average(y, weights=w):.3f}; pre-onset cells {np.average(d[d.cp == 'CP1'].hard, weights=d[d.cp == 'CP1'].n):.3f}.", "",
         "## 1 Which axis does the 'expect hard' judgment follow?", "",
         "| axis | held out (registered folds) |", "|---|---|"]
    for k, v in res.items():
        L.append(f"| {k} | {v:.4f} |")
    L += [f"| chance | {chance:.4f} |", "",
          f"Best: {best}. TTC minus looming {diff:+.4f}: **{ax_verdict}** (margin 0.01).", "",
          "## 2 The boundary on TTC", "",
          f"Full-sample fit on -log TTC: lapse {1 / (1 + np.exp(-th[0])):.3f}; **the TTC at which half"
          f" the participants expect hard braking: {t50:.2f} s**, spread {np.exp(th[2]):.2f} log units.", "",
          "| TTC at the response moment [s] | responses | share expecting hard | among those who would"
          " intervene |", "|---|---|---|---|"]
    for _, r in by_ttc.iterrows():
        L.append(f"| {r.ttc_true:.1f} | {int(r.n)} | {r.hard:.3f} | {r.hard_given_int:.3f} |")
    L += ["", "Compare: the first study's button design, own action, clip level: 50% say \"hard\" at TTC"
          " 3.3 s at the press (card NC.3j).", ""]
    (OUT / "nc3l_expected_hard_study2.md").write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
