"""
Card NC.4b -- the gate on real traffic, read EARLIER: 2 s and 3 s before the lane switch.

THE PRE-REGISTRATION. Written 2026-09-25, after card NC.4, before this was computed.

WHY. Card NC.4 read the gate 1 s before the cutter's centre crosses into the follower's lane and
found it saturated (mean 0.92 to 0.98 in every quintile): at that moment the cutter is mid-lane-
change, so the gate had nothing to discriminate (AUC 0.516) and could not contribute (gate x core
minus core -0.012 [-0.034, +0.006]). That is a flaw of the moment chosen, not a test of the gate.
The gate is graded only while the cutter is still well inside its own lane: this card reads it
2 s and 3 s before the switch.

WHAT IS COMPUTED. Card NC.4's extraction, unchanged, with the reading moment k = q - 2 s and
q - 3 s (the follower tracked from k - 1 s); the early response = a qualifying episode (1.0 m/s^2,
0.12 s) starting in [k, q). Same predictors (core, gate, gate x core), same rule, per moment.

THE RULE. The GATE CONTRIBUTES at a moment if AUC(gate x core) - AUC(core) > 0 with a 95% bootstrap
interval over recordings excluding zero. Report the gate's spread at each moment: if its mean is
still above 0.9 in four of five quintiles, the moment is again SATURATED and no verdict is drawn.

PREDICTIONS. At 3 s before the switch the gate is graded (mean 0.3 to 0.8) and CONTRIBUTES; at 2 s
it contributes less. Early responses (in the 2 or 3 s before the switch) remain a small share.

Output: replication/czb/out/nc4b_earlier.md
Run:    python replication/czb/nc4b_earlier.py
"""
from __future__ import annotations

import sys
import time
import warnings
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import norm

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import nc4_pre_switch as M  # noqa: E402

OUT = HERE / "out"
CACHE = Path(r"C:\JonasLocal\D_Data_derived\nc4b_events_{k}.pkl")


def work(args):
    rec, k = args
    M.LEAD_K, M.BACK = k, k + 25
    return M.extract(rec)


def main() -> None:
    warnings.filterwarnings("ignore")
    t0 = time.time()
    e_sorted = np.sort(np.load(M.JJ9)["X"][:, 0])
    surv = lambda x: 1.0 - np.searchsorted(e_sorted, np.asarray(x, float), side="right") / len(e_sorted)  # noqa: E731
    L = ["# Card NC.4b -- the gate on real traffic, read 2 s and 3 s before the lane switch", "",
         "Generated by `replication/czb/nc4b_earlier.py`; pre-stated in its docstring before the run."
         " Aggregates only. Do not edit by hand.", ""]
    rng = np.random.default_rng(20260925)
    for k in (50, 75):
        path = Path(str(CACHE).format(k=k))
        if path.exists():
            ev = pd.read_pickle(path)
        else:
            with ProcessPoolExecutor(max_workers=12) as ex:
                ev = pd.DataFrame([r for rr in ex.map(work, [(rec, k) for rec in range(1, 61)]) for r in rr])
            ev.to_pickle(path)
        loom = (ev.W * ev.dv / (ev.gap ** 2 + ev.W ** 2 / 4)).to_numpy(float)
        ev["core"] = norm.cdf((np.log(loom) - np.log(M.INT_LEVEL)) / M.INT_SPREAD)
        ev["gate"] = surv(ev.l0.to_numpy(float) + ev.ldot.to_numpy(float) * M.T)
        ev["both"] = ev.core * ev.gate
        y = ev.early.to_numpy(bool)
        A = {c: M.auc(ev[c].to_numpy(float), y) for c in ("core", "gate", "both")}
        recs = ev.rec.unique()
        diffs = []
        for _ in range(200):
            idx = np.concatenate([np.flatnonzero(ev.rec.to_numpy() == r) for r in rng.choice(recs, len(recs))])
            yy = y[idx]
            if yy.sum() in (0, len(yy)):
                continue
            diffs.append(M.auc(ev.both.to_numpy(float)[idx], yy) - M.auc(ev.core.to_numpy(float)[idx], yy))
        ci = np.percentile(diffs, [2.5, 97.5])
        cal = ev.assign(q=pd.qcut(ev.both, 5, labels=False, duplicates="drop")).groupby("q").agg(
            n=("early", "size"), obs=("early", "mean"), pred=("both", "mean"), gate=("gate", "mean"))
        saturated = int((cal.gate > 0.9).sum()) >= 4
        verdict = ("SATURATED (no verdict)" if saturated else
                   "the GATE CONTRIBUTES" if ci[0] > 0 else "the gate does NOT contribute detectably")
        L += [f"## {k / 25:g} s before the switch", "",
              f"{len(ev):,} closing cut-ins; early responses (starting in the {k / 25:g} s before the switch):"
              f" {int(y.sum())} ({y.mean():.1%}). Gate: mean {ev.gate.mean():.3f}, 10th-90th percentile"
              f" {ev.gate.quantile(0.1):.3f} to {ev.gate.quantile(0.9):.3f}.", "",
              "| predictor | AUC |", "|---|---|",
              f"| core (video curve on looming) | {A['core']:.3f} |",
              f"| gate (JJ.9, empirical highD) | {A['gate']:.3f} |",
              f"| **gate x core** | **{A['both']:.3f}** |", "",
              f"gate x core minus core {A['both'] - A['core']:+.3f} [{ci[0]:+.3f}, {ci[1]:+.3f}]: **{verdict}**.", "",
              "| quintile of gate x core | events | mean gate | predicted | observed |", "|---|---|---|---|---|"]
        for q, r in cal.iterrows():
            L.append(f"| {int(q) + 1} | {int(r.n)} | {r.gate:.3f} | {r.pred:.3f} | {r.obs:.3f} |")
        L.append("")
        print(f"{k} done [{time.time() - t0:.0f} s]", flush=True)
    L += [f"Run time {time.time() - t0:.0f} s.", ""]
    (OUT / "nc4b_earlier.md").write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
