"""
Card NC.5-tau, the highD half -- the released model's own tau^-1 preference, read pointwise, as the
axis for real followers' responses to cut-ins.

THE PRE-REGISTRATION. Written 2026-09-24, after cards NC.3 and NC.3c (inverse TTC beats looming on
real highD cut-ins), before this quantity was computed on any event.

WHY. The released preference contains a one-sided Gaussian over inverse tau (`aidriver.preferences`:
tau_inv_mu 0.2 s^-1, i.e. no cost while TTC exceeds 5 s; tau_inv_sd 0.125). On the video it failed
only when SUMMED over a horizon (cards JJ.5b, JJ.12). Real followers' responses are ordered by
inverse TTC (NC.3). So the released term, read at the event, is the natural candidate for the axis
in real traffic -- unless its one-sided floor at 5 s makes it blind where most real cut-ins are.

WHAT IS COMPUTED. Card NC.3's cached events, censoring and primary detector; closing cut-ins.
tau^-1 = dv / gap (bumper gap; the released `inverse_tau` subtracts the ego length from a
centre-to-centre dx, which is the same quantity). The released residual
eps_tau = 1/2 ((max(tau^-1, 0.2) - 0.2) / 0.125)^2, zero at TTC >= 5 s. Reported: the share of
events with eps_tau = 0 and their response rate; AUC of eps_tau (ties at zero counted as ties)
against NC.3's AUC of -log TTC (0.739) and of looming (0.713); the response rate by TTC band.

THE RULE. The released tau^-1 term is the axis in real traffic if its AUC is within 0.01 of the
TTC axis's; BLIND BY ITS FLOOR if more than half of the responses occur at eps_tau = 0.

PREDICTION. BLIND BY ITS FLOOR: highD's closing cut-ins have median TTC of about 26 s (gap 68 m,
dv 2.65 m/s), so most events, and most responses, sit at TTC > 5 s where the released term is
exactly zero; its AUC falls well short of TTC's (0.60 to 0.65).

Output: replication/czb/out/nc5_tau_highd.md
Run:    python replication/czb/nc5_tau_highd.py   (needs card NC.3's cache)
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import nc3_highd_cutins as N  # noqa: E402

OUT = HERE / "out"
MU, SD = 0.2, 0.125
NC3_AUC_TTC, NC3_AUC_LOOM = 0.739, 0.713


def main() -> None:
    _, ev = pd.read_pickle(N.CACHE)
    c = ev[~ev["pre_0.5_0.3"] & ~ev.lc & (ev.dv > 0)].copy()
    y = c["resp_0.5_0.3"].to_numpy(bool)
    tinv = (c.dv / c.gap).to_numpy(float)
    eps = 0.5 * ((np.maximum(tinv, MU) - MU) / SD) ** 2
    zero = eps == 0
    a_eps = N.auc(eps, y)
    a_ttc = N.auc(tinv, y)
    blind = y[zero].sum() > 0.5 * y.sum()
    near = abs(a_eps - a_ttc) <= 0.01
    verdict = ("THE AXIS" if near else "BLIND BY ITS FLOOR" if blind else "NEITHER")
    ttc = 1.0 / tinv
    bands = [0, 2, 3, 5, 10, 20, 40, np.inf]
    tab = pd.DataFrame({"band": pd.cut(ttc, bands), "y": y}).groupby("band", observed=True).y.agg(
        n="size", rate="mean")
    L = ["# Card NC.5-tau, the highD half -- the released tau^-1 preference as the axis", "",
         "Generated by `replication/czb/nc5_tau_highd.py`; pre-stated in its docstring before the"
         " run. Aggregates only. Do not edit by hand.", "",
         f"{len(c):,} closing cut-ins, {int(y.sum())} responses (card NC.3's set). The released term"
         f" is zero at TTC >= 5 s: **{zero.mean():.1%} of events and {y[zero].sum() / y.sum():.1%}"
         " of responses** sit there.", "",
         "| axis | AUC for the response |", "|---|---|",
         f"| the released tau^-1 residual, pointwise | {a_eps:.3f} |",
         f"| inverse TTC itself (this run) | {a_ttc:.3f} |",
         f"| card NC.3: -log TTC / looming | {NC3_AUC_TTC} / {NC3_AUC_LOOM} |", "",
         "| TTC band [s] | events | response rate |", "|---|---|---|"]
    for b, r in tab.iterrows():
        L.append(f"| {b} | {int(r.n)} | {r.rate:.3f} |")
    L += ["", f"**{verdict}.** The released term's AUC {a_eps:.3f} against TTC's {a_ttc:.3f}"
          f" (within 0.01: {'yes' if near else 'no'}); responses at zero cost:"
          f" {y[zero].sum()} of {int(y.sum())}.", ""]
    (OUT / "nc5_tau_highd.md").write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
