"""
Card NDS.1 -- run the shared analysis path end to end on the split-site data interface.

PRE-STATED before the run (skill section 12: decision rules before the experiment).

WHY THIS CARD EXISTS. Naturalistic data will arrive at Volvo Cars in the shape of
`transfer/interface_schema.yaml`, produced by an adapter written at VCC that never leaves
that site. That schema was derived from `docs/data_requirements.md` on paper; no analysis
code had ever read it. Decision 6 of `docs/split_site_protocol.md` asks VCC whether they
want to review the schema before adapter work starts, so any gap in it must be found NOW:
after VCC has built an adapter, a change is expensive in their calendar time and in our
credibility.

WHAT IS RUN. `src/comfortzone/interface.py` against `transfer/fixtures/synthetic/` (12
made-up events, 3 pseudonymous drivers, generated by `transfer/make_synthetic_fixture.py`).

ACCEPTANCE CRITERIA, stated before the run:

  A1  The loader reads all 12 events and their metadata without error.
  A2  Every event carrying a brake onset yields a finite theta_dot at that onset and a
      finite gate weight there.
  A3  The per-driver median theta_dot at onset preserves the ORDER of the levels the
      fixture was scripted with (D03 < D01 < D02). Order, not value: the fixture scripts
      its onsets on a DIFFERENT gap convention from the one the analysis uses, and
      quantifying that difference is the point of section 3 below, not a failure.
  A4  An event declaring `ref_point = rear_axle` raises `InterfaceGapError` rather than
      silently returning a wrong gap. The interface carries total length only, and a
      rear-axle position cannot be converted to a bumper position without the front
      overhang.

NOT DECIDED HERE. The estimator. The video paradigm's unit is a design cell (a frozen clip
and the share of raters who would intervene); naturalistic data has one driver and one
realized onset per event, so the natural observation is the axis value AT the onset, with
no-response events right-censored. That framing is query NDS.Q1, not a settled choice.

Output: replication/czb/out/nds1_interface_smoke.md. Do not edit that file by hand.
Run: python replication/czb/nds1_interface_smoke.py
"""
from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "transfer"))

from comfortzone.interface import (  # noqa: E402
    GATE_M_LAT, GATE_S_L, InterfaceGapError, T_ENC, interface_observation_table,
    interface_predictors, load_interface_dir, longitudinal_gap,
)
from make_synthetic_fixture import DRIVERS, W_OTH  # noqa: E402

FIXTURE = ROOT / "transfer" / "fixtures" / "synthetic"
OUT = ROOT / "replication" / "czb" / "out" / "nds1_interface_smoke.md"


def main() -> int:
    L: list[str] = []
    verdicts: list[tuple[str, bool, str]] = []

    def criterion(name: str, ok: bool, detail: str = "") -> None:
        verdicts.append((name, bool(ok), detail))

    L += ["# Card NDS.1 -- the shared analysis path on the split-site data interface", "",
          "Generated by `replication/czb/nds1_interface_smoke.py`; acceptance criteria "
          "pre-stated in its docstring before the run. Do not edit by hand.", ""]

    # --- A1 ---------------------------------------------------------------------------
    meta, events = load_interface_dir(FIXTURE)
    criterion("A1 loader reads the interface directory", len(events) == 12 and len(meta) == 12,
              f"{len(events)} events, {len(meta)} metadata rows")

    obs = interface_observation_table(events)

    # --- A2 ---------------------------------------------------------------------------
    responded = obs[~obs.censored]
    a2 = bool(len(responded) > 0
              and np.isfinite(responded.theta_dot_at_onset).all()
              and np.isfinite(responded.w_gate_at_onset).all())
    criterion("A2 finite axis and gate at every brake onset", a2,
              f"{len(responded)} of {len(obs)} events carry a brake onset")

    # --- A3 ---------------------------------------------------------------------------
    per_driver = (responded.groupby("driver_id")
                  .theta_dot_at_onset.median().sort_values())
    scripted = pd.Series(DRIVERS).sort_values()
    a3 = list(per_driver.index) == list(scripted.index)
    criterion("A3 per-driver order preserved", a3,
              f"recovered {list(per_driver.index)} vs scripted {list(scripted.index)}")

    # --- A4 ---------------------------------------------------------------------------
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td) / "ra"
        shutil.copytree(FIXTURE, tmp)
        m = pd.read_csv(tmp / "events.csv")
        m["ref_point"] = "rear_axle"
        m.to_csv(tmp / "events.csv", index=False)
        _, ra_events = load_interface_dir(tmp)
        try:
            longitudinal_gap(next(iter(ra_events.values())))
            a4, a4d = False, "no error raised"
        except InterfaceGapError as e:
            a4, a4d = True, str(e).split(":", 1)[1].strip()[:70] + "..."
    criterion("A4 rear_axle refused rather than mis-computed", a4, a4d)

    # --- 1 what the loader produced ----------------------------------------------------
    L += ["## 1 What the loader produced", "",
          f"{len(events)} events, {obs.driver_id.nunique()} drivers, "
          f"scenarios {sorted(obs.scenario.unique())}. "
          f"{len(responded)} events carry a brake onset; "
          f"{int(obs.censored.sum())} are right-censored.", "",
          "| driver | events with onset | median theta_dot at onset [rad/s] | scripted level [rad/s] |",
          "|---|---|---|---|"]
    for d in sorted(DRIVERS):
        sub = responded[responded.driver_id == d]
        med = float(sub.theta_dot_at_onset.median()) if len(sub) else float("nan")
        L.append(f"| {d} | {len(sub)} | {med:.4f} | {DRIVERS[d]:.4f} |")
    L += ["",
          "The recovered values are systematically ABOVE the scripted ones. That is not an "
          "error in either: the fixture and the analysis use different gap conventions, "
          "which section 3 decomposes. It is the finding this card exists to produce.", ""]

    # --- 2 gate ------------------------------------------------------------------------
    L += ["## 2 The gate, carried over from card G.1 unchanged", "",
          f"`m_lat = {GATE_M_LAT} m`, `s_l = {GATE_S_L} m`, `t_enc = {T_ENC} s`, fitted on the "
          f"second cut-in study (`out/cutin2_gate.md`) and applied here without refitting.", "",
          f"Gate weight at the brake onsets: median {responded.w_gate_at_onset.median():.3f}, "
          f"range {responded.w_gate_at_onset.min():.3f} to {responded.w_gate_at_onset.max():.3f}.", ""]

    # --- 3 the convention gap ----------------------------------------------------------
    L += ["## 3 The convention gap, quantified", "",
          "The fixture scripts each onset on `theta_dot = W*dv / max(dx, 0.5)^2` with `dx` the "
          "raw longitudinal separation. The analysis path computes "
          "`theta_dot = W*dv / (gap^2 + W^2/4)` with `gap` EDGE-TO-EDGE, as every video card "
          "does. Three differences separate them, and the third is the large one.", "",
          "| difference | effect on theta_dot |", "|---|---|"]

    ev0 = events[responded.event_id.iloc[0]]
    pr0 = interface_predictors(ev0)
    i0 = int(np.argmin(np.abs(pr0.t.to_numpy() - float(responded.t_brake_onset.iloc[0]))))
    gap_edge = float(pr0.gap_m.iloc[i0])
    oth_len = float(ev0.meta["oth_len"])
    gap_raw = gap_edge + oth_len
    dv = float(pr0.v_rel.iloc[i0])
    td_exact_edge = W_OTH * dv / (gap_edge ** 2 + W_OTH ** 2 / 4.0)
    td_small_edge = W_OTH * dv / gap_edge ** 2
    td_small_raw = W_OTH * dv / gap_raw ** 2
    L += [f"| edge-to-edge vs raw separation ({gap_edge:.2f} m vs {gap_raw:.2f} m at one onset) "
          f"| x{td_small_edge / td_small_raw:.2f} |",
          f"| exact derivative vs small-angle (the `+ W^2/4` term) | x{td_exact_edge / td_small_edge:.3f} |",
          "| the fixture's scripted 0.2 s reaction delay, during which the gap keeps closing "
          "| included in both columns of section 1 |", ""]
    L += [f"So the dominant term is the **gap convention**, worth a factor of about "
          f"{td_small_edge / td_small_raw:.1f} at this onset, while the exact-derivative "
          f"correction is under a percent. A level fitted on one convention and applied "
          f"under the other is wrong by that factor. This is the single most important "
          f"thing to fix with VCC before their adapter is written.", ""]

    # --- 4 schema findings -------------------------------------------------------------
    L += ["## 4 What the interface schema is missing", "",
          "Found by writing the loader against it. Each is a change to "
          "`transfer/interface_schema.yaml`, and each is cheap now and expensive after VCC "
          "has built an adapter.", "",
          "1. **One `ref_point` column cannot serve both vehicles (NDS.Q2).** The schema "
          "carries a single `ref_point` for an event, which assumes the ego and the partner "
          "are referenced the same way. In naturalistic data they essentially never are: the "
          "ego position comes from the vehicle's own signals (rear axle or centre of gravity) "
          "and the partner's from radar or camera (typically the nearest reflecting surface). "
          "The schema needs `ego_ref_point` and `oth_ref_point` separately.",
          "2. **`rear_axle` is not resolvable to a bumper position (NDS.Q2).** Converting one "
          "needs the front overhang; the schema carries only total length. Either add "
          "`ego_front_overhang` / `oth_front_overhang`, or state that positions are delivered "
          "at the vehicle centre. The loader raises rather than guessing.",
          "3. **The lateral frame of `ego_y` and `oth_y` is ambiguous (NDS.Q3).** The schema "
          "calls `ego_y` a 'signed lateral offset from lane center (preferred)' and `oth_y` a "
          "'partner lateral position'. The gate needs their DIFFERENCE, so both must be in one "
          "frame. If the ego's is lane-relative and the partner's is absolute, `l0` is wrong "
          "by the ego's own lane offset, which is exactly the quantity that varies during a "
          "cut-in.",
          "4. **`t_brake_onset` has no stated criterion (NDS.Q4).** The axis value at the "
          "onset is the observation, so the onset definition sets the level. A pedal-switch "
          "criterion and a deceleration-threshold criterion differ by a few tenths of a "
          "second, and the gap closes throughout. The schema should carry the criterion as a "
          "field, or fix one in the protocol.",
          "5. **`valid` is not required to hold at the onset (NDS.Q5).** The partner track may "
          "be interpolated exactly where the observation is read. The loader reports "
          "`valid_at_onset`; the analysis should exclude or flag those events, and the "
          "schema should say so.", ""]
    n_default = int(obs.geometry_default.sum())
    L += [f"A sixth point is a caution rather than a gap: `theta_dot` scales linearly with the "
          f"partner's width, so a class-default width propagates straight into the axis. "
          f"`geometry_default` flags it ({n_default} of {len(obs)} events here), and the "
          f"analysis should report what share of its events carry defaulted geometry.", ""]

    # --- 5 verdicts --------------------------------------------------------------------
    L += ["## 5 The pre-stated acceptance criteria", "", "| criterion | result | detail |",
          "|---|---|---|"]
    for name, ok, detail in verdicts:
        L.append(f"| {name} | {'PASS' if ok else 'FAIL'} | {detail} |")
    n_ok = sum(ok for _, ok, _ in verdicts)
    L += ["", f"**{n_ok} of {len(verdicts)} criteria met.**", ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))
    print(f"\nwrote {OUT.relative_to(ROOT)}")
    return 0 if n_ok == len(verdicts) else 1


if __name__ == "__main__":
    sys.exit(main())
