"""Card C: how much does the percentile choice matter, in seconds of trigger onset?

The deliverable of stage 1 is a population percentile of the boundary level ("trigger
where q% of drivers would already be uncomfortable"). Jonas's standing concern is that
the CHOICE of q may matter more than the estimation of the boundary itself. This
script quantifies that on the three Random cut-in stimuli: for each percentile level
(and its CI), the implied trigger onset is the first time the running-max deficit
crosses the level, and the sensitivity is reported in the unit that matters
operationally -- seconds of onset shift per 5 percentile points, against the onset
shift implied by the percentile's own estimation uncertainty.

Specification (per the R.1.Q1 convention): hierarchical-lapse variant, k = 12,
shown-window covariates -- the card A.2.v2 configuration, refitted live by the same
code path so the numbers regenerate with the data. The comfort and dread levels from
the ordered braking-expectation model are included as reference rows, translated to
equivalent required deceleration by the same approximation stage 1 uses.

Standing caveat (review gate R.2, 2026-08-29, `docs/r2_gate_decisions.md`): the
deficit axis these levels live on is well estimated ON ITS OWN SCALE, but the field's
kinematic content was ruled against by the pre-registered comparison on the second
cut-in study. The sensitivity below is therefore a property of the deliverable as
currently constructed, not evidence for the axis.

Run:  python replication/czb/percentile_sensitivity.py
Outputs: replication/czb/out/percentile_sensitivity.md,
         figures/percentile_sensitivity.png
"""
from __future__ import annotations

import sys
import time
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(HERE))

from comfortzone.czb_data import (RANDOM_CLIP_LEAD_S, RANDOM_CUTIN_TRACES,  # noqa: E402
                                  random_cutin_trials, stimulus_field)
from fit_recovery import priors_for  # noqa: E402
from fit_stage1 import (deficit_to_a_req, fit_hier_lapse, fit_ordered,  # noqa: E402
                        percentiles_with_ci)

OUT = HERE / "out" / "percentile_sensitivity.md"
FIG = REPO / "figures" / "percentile_sensitivity.png"


def onset_time(field, level: float) -> float:
    """First time since manoeuvre onset at which deficit_max crosses `level`.

    Interpolated between frames; NaN when the clip never reaches the level. Times are
    on the t_since_onset axis, so 0 is manoeuvre onset.
    """
    t = field.t_since_onset.to_numpy()
    d = field.deficit_max.to_numpy()
    above = d >= level
    if not above.any():
        return float("nan")
    i = int(np.argmax(above))
    if i == 0:
        return float(t[0])
    # linear interpolation on the rising segment
    t0, t1, d0, d1 = t[i - 1], t[i], d[i - 1], d[i]
    return float(t0 + (level - d0) / max(d1 - d0, 1e-9) * (t1 - t0))


def main() -> None:
    t_start = time.time()
    r = random_cutin_trials()
    pid = r.participant.factorize()[0].astype(int)
    x = r.deficit_max.to_numpy(float)
    y = r.intervene.to_numpy(float)
    pr = priors_for(x)
    print("fitting stage 1 (hier lapse) ...", flush=True)
    f = fit_hier_lapse(x, y, pid, pr)
    print("fitting the ordered model for comfort/dread ...", flush=True)
    y_ord = r.braking_expectation.fillna(0).to_numpy()
    ordered = fit_ordered(x, y_ord, pid, pr)

    fields = {c: stimulus_field(p, accum_lead_s=RANDOM_CLIP_LEAD_S)
              for c, p in RANDOM_CUTIN_TRACES.items()}
    crits = list(fields)

    pcts = percentiles_with_ci(f)
    rows = []
    for q, val, lo, hi in pcts:
        onsets = {c: onset_time(fields[c], val) for c in crits}
        d_ci = {c: onset_time(fields[c], hi) - onset_time(fields[c], lo) for c in crits}
        rows.append((q, val, lo, hi, onsets, d_ci))

    L = ["# Card C — percentile sensitivity of the trigger onset",
         "",
         "Generated by `replication/czb/percentile_sensitivity.py`. Specification: "
         "hierarchical lapse, k = 12, shown-window covariates (the A.2.v2 "
         "configuration, refitted live). Onset times are seconds since manoeuvre "
         "onset at which the running-max deficit crosses the level; NaN means the "
         "clip never reaches it. Do not edit by hand.",
         "",
         "**Standing caveat (gate R.2):** these levels are well estimated on their "
         "own scale; the axis itself was ruled against as a mechanism by the "
         "pre-registered field-versus-gap comparison. This table is about the "
         "deliverable's sensitivity, not the axis's validity.",
         "",
         "## Implied trigger onset per stimulus [s since onset]",
         "",
         "| percentile | level | " + " | ".join(f"{c}" for c in crits)
         + " | " + " | ".join(f"{c} CI-width [s]" for c in crits) + " |",
         "|---|---|" + "---|" * (2 * len(crits))]
    for q, val, lo, hi, onsets, d_ci in rows:
        L.append(f"| {q}th | {val:.0f} | "
                 + " | ".join(f"{onsets[c]:.2f}" for c in crits) + " | "
                 + " | ".join(f"{d_ci[c]:.2f}" for c in crits) + " |")

    # sensitivity per 5 percentile points, versus the CI-implied onset spread
    L += ["", "## The comparison the card asks for",
          "",
          "| stimulus | mean d(onset)/d(5 pct pts) [s] | max | mean onset shift "
          "across the 95% CI [s] |", "|---|---|---|---|"]
    verdict_bits = []
    for c in crits:
        o = np.array([rows[i][4][c] for i in range(len(rows))])
        steps = np.diff(o)
        ci_w = np.array([rows[i][5][c] for i in range(len(rows))])
        finite = np.isfinite(steps)
        m_step = float(np.nanmean(np.abs(steps[finite]))) if finite.any() else float("nan")
        mx_step = float(np.nanmax(np.abs(steps[finite]))) if finite.any() else float("nan")
        m_ci = float(np.nanmean(ci_w))
        L.append(f"| {c} | {m_step:.3f} | {mx_step:.3f} | {m_ci:.3f} |")
        verdict_bits.append((c, m_step, m_ci))

    ratio = np.nanmean([b[1] / max(b[2], 1e-9) for b in verdict_bits])
    L += ["",
          f"**Reading (computed).** Averaged over stimuli, one 5-point step of the "
          f"percentile choice moves the trigger onset by "
          f"{np.nanmean([b[1] for b in verdict_bits]):.3f} s, which is "
          f"{ratio:.1f}x the onset shift implied by the percentile's own estimation "
          f"uncertainty ({np.nanmean([b[2] for b in verdict_bits]):.3f} s). "
          + ("The CHOICE of percentile dominates the estimation error, confirming "
             "the standing concern: which percentile to use is the consequential "
             "decision, and it is a policy question, not a statistical one."
             if ratio > 2 else
             "The choice of percentile and its estimation error are of comparable "
             "size, so neither dominates."),
          ""]

    # comfort / dread reference rows
    c_comfort = float(np.exp(ordered["mu"]))
    c_dread = c_comfort + float(ordered["delta"])
    L += ["## Reference: the ordered model's comfort and dread levels", "",
          "| level | deficit | equivalent a_req [m/s2] | "
          + " | ".join(f"onset {c} [s]" for c in crits) + " |",
          "|---|---|---|" + "---|" * len(crits)]
    for name, lev in (("comfort (median)", c_comfort), ("dread (median)", c_dread)):
        L.append(f"| {name} | {lev:.0f} | {deficit_to_a_req(lev):.2f} | "
                 + " | ".join(f"{onset_time(fields[c], lev):.2f}" for c in crits) + " |")

    # figure
    fig, ax = plt.subplots(figsize=(8, 4.5))
    colors = {"TTC4": "#c1272d", "TTC6": "#e69f00", "TTC8": "#0072b2"}
    for c in crits:
        fld = fields[c]
        m = (fld.t_since_onset >= -0.5) & (fld.t_since_onset <= 2.0)
        ax.plot(fld.t_since_onset[m], fld.deficit_max[m], color=colors.get(c, "k"),
                label=c)
    for q, val, lo, hi, _, _ in rows:
        if q in (50, 80, 95):
            ax.axhline(val, color="gray", lw=0.8, ls="--")
            ax.text(2.02, val, f"{q}th", va="center", fontsize=8, color="gray")
            ax.axhspan(lo, hi, color="gray", alpha=0.12)
    ax.set_xlabel("time since manoeuvre onset [s]")
    ax.set_ylabel("running-max deficit")
    ax.set_title("Percentile levels (50/80/95th, with CIs) against the three stimuli")
    ax.legend(frameon=False)
    fig.tight_layout()
    fig.savefig(FIG, dpi=150)

    L.append(f"\nFigure: `figures/percentile_sensitivity.png`. "
             f"Runtime {(time.time() - t_start) / 60:.1f} min.")
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L[-25:]))


if __name__ == "__main__":
    main()
